packages:
  - apps/*
  - packages/*
  - templates/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  kysely: ^0.29.5
  happy-dom: ^20.11.6
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
  vue: ^3.5.41
  "@tailwindcss/vite": ^4.3.3
  tailwindcss: ^4.3.3
  jeep-sqlite: ^2.8.0
  sql.js: 1.13.0
  unplugin-auto-import: ^21.1.0
  unplugin-vue-components: ^32.1.0
  unplugin-icons: ^23.0.1
  "@intlify/unplugin-vue-i18n": ^11.2.5
  "@vueuse/core": ^14.4.0
  "@capacitor/android": ^8.5.0
  "@sqlite.org/sqlite-wasm": 3.53.0-build1
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.0"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.0"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.0"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.0"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.0"
  - vite-plus@0.3.0
allowBuilds:
  esbuild: true
