/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/shared/components/error/404.vue')['default']
    DemoBusLog: typeof import('./src/modules/demo/components/DemoBusLog.vue')['default']
    DemoCreateOrderSheet: typeof import('./src/modules/demo/components/DemoCreateOrderSheet.vue')['default']
    DemoOrderList: typeof import('./src/modules/demo/components/DemoOrderList.vue')['default']
    DemoPipelineBenchmark: typeof import('./src/modules/demo/components/DemoPipelineBenchmark.vue')['default']
    DemoStatCards: typeof import('./src/modules/demo/components/DemoStatCards.vue')['default']
    DemoView: typeof import('./src/modules/demo/views/DemoView.vue')['default']
    F7App: typeof import('framework7-vue')['f7App']
    F7Block: typeof import('framework7-vue')['f7Block']
    F7BlockTitle: typeof import('framework7-vue')['f7BlockTitle']
    F7Button: typeof import('framework7-vue')['f7Button']
    F7Chip: typeof import('framework7-vue')['f7Chip']
    F7Fab: typeof import('framework7-vue')['f7Fab']
    F7FabButton: typeof import('framework7-vue')['f7FabButton']
    F7FabButtons: typeof import('framework7-vue')['f7FabButtons']
    F7Icon: typeof import('framework7-vue')['f7Icon']
    F7Link: typeof import('framework7-vue')['f7Link']
    F7List: typeof import('framework7-vue')['f7List']
    F7ListInput: typeof import('framework7-vue')['f7ListInput']
    F7ListItem: typeof import('framework7-vue')['f7ListItem']
    F7Navbar: typeof import('framework7-vue')['f7Navbar']
    F7NavRight: typeof import('framework7-vue')['f7NavRight']
    F7Page: typeof import('framework7-vue')['f7Page']
    F7PageContent: typeof import('framework7-vue')['f7PageContent']
    F7Panel: typeof import('framework7-vue')['f7Panel']
    F7Searchbar: typeof import('framework7-vue')['f7Searchbar']
    F7Segmented: typeof import('framework7-vue')['f7Segmented']
    F7Sheet: typeof import('framework7-vue')['f7Sheet']
    F7Stepper: typeof import('framework7-vue')['f7Stepper']
    F7Subnavbar: typeof import('framework7-vue')['f7Subnavbar']
    F7SwipeoutActions: typeof import('framework7-vue')['f7SwipeoutActions']
    F7SwipeoutButton: typeof import('framework7-vue')['f7SwipeoutButton']
    F7Tab: typeof import('framework7-vue')['f7Tab']
    F7Tabs: typeof import('framework7-vue')['f7Tabs']
    F7Toggle: typeof import('framework7-vue')['f7Toggle']
    F7Toolbar: typeof import('framework7-vue')['f7Toolbar']
    F7View: typeof import('framework7-vue')['f7View']
    F7Views: typeof import('framework7-vue')['f7Views']
    FeatureDetailView: typeof import('./src/modules/home/views/FeatureDetailView.vue')['default']
    HomeView: typeof import('./src/modules/home/views/HomeView.vue')['default']
    MetricsPanel: typeof import('./src/shared/components/metrics/MetricsPanel.vue')['default']
    OrderDetailView: typeof import('./src/modules/demo/views/OrderDetailView.vue')['default']
    OrderSearchView: typeof import('./src/modules/demo/views/OrderSearchView.vue')['default']
    SettingsView: typeof import('./src/modules/settings/views/SettingsView.vue')['default']
  }
}
