import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

/** Never part of the fingerprint: generated, installed, or platform-specific. */
const SKIP = new Set(["node_modules", "dist", "android", "ios", ".git", "pnpm-lock.yaml"]);

/**
 * Regenerated by every build from the source they describe, and not byte-identical run to run.
 * Including them would fail the guard on a CI machine that merely built the template.
 */
const DERIVED = new Set(["auto-imports.d.ts", "components.d.ts"]);

function walk(dir, base, files = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name < b.name ? -1 : 1,
  )) {
    if (SKIP.has(entry.name) || DERIVED.has(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, base, files);
    else files.push(relative(base, full).split(sep).join("/"));
  }
  return files;
}

/**
 * A content hash of every template, used to prove that `@cavulsqa/create` was republished after the
 * templates changed.
 *
 * The creator bundles the templates at pack time, so a template fix reaches nobody until a new
 * version of the creator goes out. Nothing about that is visible in a diff, which is exactly the
 * kind of coupling that gets forgotten — so it is checked instead of remembered.
 */
export function fingerprintTemplates(templatesRoot) {
  const hash = createHash("sha256");
  for (const file of walk(templatesRoot, templatesRoot)) {
    hash.update(file);
    hash.update("\0");
    // Line endings are normalised: git checks out CRLF on Windows and LF on the runner, and the
    // templates are the same templates either way.
    hash.update(
      readFileSync(join(templatesRoot, ...file.split("/")))
        .toString("binary")
        .replace(/\r\n/g, "\n"),
    );
    hash.update("\0");
  }
  return `sha256-${hash.digest("base64")}`;
}
